spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/demo #파일 기반, 로컬에 h2 db 설치 필요
    url: jdbc:h2:mem:demo #메모리 기반
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  config: classpath:log4j2-spring.xml
  charset:
    console: UTF-8
    file: UTF-8
  level:
    default: debug

springdoc:
  swagger-ui:
    path: /docs
